name: Demo Workflow
on: workflow_dispatch
jobs: 
  print: 
    runs-on: windows-latest
    steps: 
      - name: Print to console
        run: echo Hello People
      - name: Print a few lines
        run: |
          echo First line
          echo Second Line
